cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
dynmap-border-hideByDefault: false
dynmap-border-priority: 0
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids: []
fill-memory-tolerance: 500
prevent-block-place: false
prevent-mob-spawn: false
worlds:
  world:
    x: -160.0
    z: -192.0
    radiusX: 8000
    radiusZ: 8000
    wrapping: false
  world_nether:
    x: -8.0
    z: -8.0
    radiusX: 1000
    radiusZ: 1000
    wrapping: false
  world_the_end:
    x: 0.0
    z: 0.0
    radiusX: 1000
    radiusZ: 1000
    wrapping: false
